import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <p className={styles.placeholder}>
          thatguybryan.com | This website is getting a full update soon.
        </p>
      </main>
    </div>
  )
}

export default Home
